sudo: required
dist: trusty
language: node_js
node_js:
  - "stable"
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y libappindicator1 fonts-liberation libxss1 libindicator7
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm install -g gulp
script: gulp
env:
- secure: "jgo/F9pJWtdbGfEbCHCi4CqrajzAzlYjWX3LWJ165+dXTHUNoG9dg5ii7s01PdtYW09yAB5gS341gUmPnHY5GEBW4B9KGjte8ZG7M58RNe/Rf5eFcPtzXYQkRK2g6Prpv4zku46VgvoRm0UQpSmq6XgjEIFuRTIbFkS9GeRISyJB9HRitu4zM+sPo5d9sV1O9Cv1+jCwPgyVtpQyimNpwwGSpJgN3xrbrfGK2dBJHFbgJGSZBxRbplq2YgZWOhrmKnPUiSUCZOxy1dWAsZjj4tjxSRVmR3qGax9QN+2HWE/35nwQ0zXrrdYADaYsKwdYMi5VbYSBsgvLZJMHQTx2LzdXDfRMM3D4ZCFfg61Tvzei5aZ4jytf5/L5331ExNNUSM8TJkYLOWyMRiohMrLd2SZfhyEqq2C8bFqG0/0FX1LROvMyKWlBHxVS6OI4yE74V8da7s+fGw0svrrYELx4ov3otR5OxfOniPkT4XEulRlj07jtXXMiNBUFaXWKdIDkzBMe82kZePvR44uo4ZuaCKWrLc+7EIuqPQ7Hp7c55JRnj1qh+sVI2/0QQDSfQzlDsraIZdGh7TyZtcFFimI4fZtc+3iLnzF9AfVJZAz7sWZcad5RB339a4kYCjFtgry8o3bKe2+4kwTN3C6MfcAn3wOYHJYpylQylRPduA5qTAo="
before_install:
  - sudo pip install codecov
after_success:
  - codecov
  - ./deploy-jsdoc.sh

